name: Compress_and_Push
on: [ push ]

jobs:
  
  # Job 1. Compress and Push
  compress_and_push:

    runs-on: ubuntu-latest
    name: Compress and Push

    steps:

      # Step 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2. Execute Unbuntu Commands
      - name: Execute Ubuntu Commands
        run: |
          rm web/archive.zip
          zip -r web/archive.zip web
        shell: bash

      # Step 3. Push to GitHub
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          now=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "GitHub Action, ${now}"
          git push