name: Run_Python_Regularly
on:
  push: 
  workflow_dispatch: 
  schedule:
    - cron: "0 * * * *"

jobs:

  # Job 1. Set up python environment and run python
  run_python:

    runs-on: ubuntu-latest
    name: Run Python

    steps:

      # Step 1. Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2. Set up python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5" # Python Version

      # Step 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4. Run python
      - name: Run Python
        run: |
          python src/baidu_hot_search.py
          python src/mfc_cn.py

      # Step 5. Push to GitHub
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          now=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "GitHub Action, ${now}"
          git push